using System;

namespace DetPS2.Core;

/// <summary>
/// Host audio pull interface (Phase 17). Core never opens devices or uses host clocks.
/// Desktop implements playback; tests use <see cref="NullAudioSink"/> or <see cref="CapturingAudioSink"/>.
/// </summary>
public interface IAudioSink
{
    /// <summary>Receive interleaved stereo PCM16 samples generated by SPU2.</summary>
    void Submit(ReadOnlySpan<short> interleavedStereo);
}

public sealed class NullAudioSink : IAudioSink
{
    public void Submit(ReadOnlySpan<short> interleavedStereo) { }
}

/// <summary>Test sink: records sample count and last peak.</summary>
public sealed class CapturingAudioSink : IAudioSink
{
    public long SamplesReceived { get; private set; }
    public short LastPeak { get; private set; }

    public void Submit(ReadOnlySpan<short> interleavedStereo)
    {
        SamplesReceived += interleavedStereo.Length;
        for (int i = 0; i < interleavedStereo.Length; i++)
        {
            short a = Math.Abs(interleavedStereo[i]);
            if (a > LastPeak) LastPeak = a;
        }
    }

    public void Reset()
    {
        SamplesReceived = 0;
        LastPeak = 0;
    }
}

/// <summary>
/// Ring-buffer sink for host playback (Phase 17 Desktop).
/// Core pushes samples; host drains when ready. No host clock in core path.
/// </summary>
public sealed class RingBufferAudioSink : IAudioSink
{
    private readonly short[] _buffer;
    private int _write;
    private int _read;
    private int _count;
    private readonly object _lock = new();

    public long SamplesReceived { get; private set; }
    public int Capacity => _buffer.Length;
    public int Available
    {
        get { lock (_lock) return _count; }
    }

    public RingBufferAudioSink(int capacitySamples = 48000 * 2) // ~1s stereo
    {
        if (capacitySamples < 256) capacitySamples = 256;
        _buffer = new short[capacitySamples];
    }

    public void Submit(ReadOnlySpan<short> interleavedStereo)
    {
        lock (_lock)
        {
            for (int i = 0; i < interleavedStereo.Length; i++)
            {
                if (_count >= _buffer.Length)
                {
                    // Drop oldest sample to keep newest (deterministic overflow policy)
                    _read = (_read + 1) % _buffer.Length;
                    _count--;
                }
                _buffer[_write] = interleavedStereo[i];
                _write = (_write + 1) % _buffer.Length;
                _count++;
                SamplesReceived++;
            }
        }
    }

    /// <summary>Copy up to max samples into dest; returns count written.</summary>
    public int Drain(Span<short> dest)
    {
        lock (_lock)
        {
            int n = Math.Min(dest.Length, _count);
            for (int i = 0; i < n; i++)
            {
                dest[i] = _buffer[_read];
                _read = (_read + 1) % _buffer.Length;
            }
            _count -= n;
            return n;
        }
    }

    public void Reset()
    {
        lock (_lock)
        {
            _write = _read = _count = 0;
            SamplesReceived = 0;
            Array.Clear(_buffer);
        }
    }
}
